### ISSUE TITLE
Face mask and Hairstyle not change

### ISSUE THREAD

**Issue by dimdimdimka** [tera-mods/elin-magic#2]
I am using tera toolbox in it the elin magiс module, not your product, but there are no issues on the caali-hackerman page. Mask change does not work displays 'costume updated:' after the colon is empty. And Hairstyle in the fitting room doesn't show ID and doesn't work. Body, weapon, back work. Hide mask function work. Maybe am I doing something wrong? Sorry for Google Translate.

**Comment by pinkipi** [comment]
This is an issue with TERA Toolbox, not elin-magic. If you want a working version, use [TERA Proxy](https://github.com/tera-proxy/tera-proxy) instead.
